apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: terraform-provider-rhcs-wylc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: terraform-provider-rhcs-wylc
    app.kubernetes.io/part-of: appstudio
  name: terraform-provider-rhcs-wjt6f
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: terraform-provider-rhcs-wylc
    weight: null
status: {}
